import { API_BASE, PHQ9A_ITEMS, GAD7_ITEMS, K10_ITEMS, ASQ_ITEMS, PHQ_GAD_CHOICES, K10_CHOICES } from "./survey_config.js";
import { sum, bandPHQ9, bandGAD7, bandK10, phqBandLabel, gadBandLabel, k10BandLabel, computeOverallTier } from "./survey_scoring.js";

const REGIONS=["서울특별시","부산광역시","대구광역시","인천광역시","광주광역시","대전광역시","울산광역시","세종특별자치시","경기도","강원특별자치도","충청북도","충청남도","전북특별자치도","전라남도","경상북도","경상남도","제주특별자치도"];
const STEPS=["지역 선택","이용 안내","우울 신호","불안 신호","스트레스 신호","안전 확인"];
const state={step:0,region:"",phq:Array(9).fill(null),gad:Array(7).fill(null),k10:Array(10).fill(null),asq:Array(4).fill(null),result:null,loading:false,error:""};
const $=(id)=>document.getElementById(id);
const container=$("step-container"),prev=$("prev-button"),next=$("next-button"),modal=$("crisis-modal");

function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function progress(){return Math.round(((state.step+1)/STEPS.length)*100);}
function answered(arr){return arr.filter(v=>v!==null).length;}
function currentCompletion(){if(state.step===0)return state.region?1:0;if(state.step===1)return 1;if(state.step===2)return answered(state.phq)/9;if(state.step===3)return answered(state.gad)/7;if(state.step===4)return answered(state.k10)/10;return answered(state.asq)/4;}
function complete(){return currentCompletion()===1;}

function renderShell(){
  const pct=progress();$("progress-percent").textContent=`${pct}%`;$("progress-bar").style.width=`${pct}%`;$("step-label").textContent=`${state.step+1} / ${STEPS.length} 단계`;
  $("step-list").innerHTML=STEPS.map((name,i)=>`<li class="step-item ${i===state.step?"active":i<state.step?"done":""}"><span class="step-number">${i<state.step?"✓":i+1}</span><span class="step-name">${name}</span></li>`).join("");
  prev.disabled=state.step===0||state.loading;next.disabled=!complete()||state.loading;next.innerHTML=state.step===5?(state.loading?"분석 중…":"결과 분석하기 <span>→</span>"):"다음 단계 <span>→</span>";
  const done=Math.round(currentCompletion()*100);$("answer-status").textContent=state.step>1&&state.step!==5?`현재 단계 ${done}% 응답 완료`:"";
}

function header(kicker,title,desc){return `<p class="section-kicker">${kicker}</p><h2>${title}</h2><p class="section-description">${desc}</p>`;}
function renderRegion(){container.innerHTML=header("STEP 01 · REGION","어느 지역에 거주하고 있나요?","선택한 지역은 개인 위험도 계산에 사용되지 않으며, 결과에서 지역 통계 지도로 이동할 때만 활용됩니다.")+`<label class="form-label" for="region">거주 지역</label><select id="region" class="region-select"><option value="">지역을 선택해주세요</option>${REGIONS.map(r=>`<option ${state.region===r?"selected":""}>${r}</option>`).join("")}</select><div class="info-grid"><article class="info-tile"><span>01</span><strong>약 5분 소요</strong><p>네 가지 표준 선별 척도를 단계별로 진행합니다.</p></article><article class="info-tile"><span>02</span><strong>별도 저장 없음</strong><p>응답은 서버나 브라우저 저장소에 남기지 않습니다.</p></article><article class="info-tile"><span>03</span><strong>결과 바로 확인</strong><p>점수와 ML 위험 신호를 한 화면에서 확인합니다.</p></article></div>`;$("region").onchange=e=>{state.region=e.target.value;render();};}
function renderIntro(){container.innerHTML=header("STEP 02 · BEFORE YOU BEGIN","시작하기 전에 확인해 주세요.","이 서비스는 현재 상태를 스스로 살펴보는 선별 도구이자 머신러닝 파이프라인 데모입니다.")+`<div class="info-grid"><article class="info-tile"><span>✓</span><strong>진단이 아닙니다</strong><p>결과는 참고 정보이며 의료인의 진단을 대신하지 않습니다.</p></article><article class="info-tile"><span>↗</span><strong>솔직하게 응답</strong><p>최근 2주 또는 4주의 상태에 가장 가까운 답을 골라주세요.</p></article><article class="info-tile"><span>♡</span><strong>안전 우선</strong><p>위험 신호가 확인되면 즉시 이용 가능한 도움을 안내합니다.</p></article></div><div class="notice"><span>!</span><div><strong>합성 데이터 기반 기술 데모</strong>ML 확률은 실제 임상 데이터가 아닌 합성 데이터로 학습한 결과이므로 실제 질환 가능성을 의미하지 않습니다.</div></div>`;}

function renderScale(type,title,desc,items,arr,choices,max,labeler){
  container.innerHTML=header(`STEP 0${state.step+1} · ${type}`,title,desc)+`<div class="question-list">${items.map((q,i)=>`<article class="question-card"><p class="question-title"><span class="question-index">${String(i+1).padStart(2,"0")}</span><span>${escapeHtml(q)}</span></p><div class="choice-grid">${choices.map(c=>`<button type="button" class="choice-button ${arr[i]===c.value?"selected":""}" data-index="${i}" data-value="${c.value}" aria-pressed="${arr[i]===c.value}">${c.label}</button>`).join("")}</div></article>`).join("")}</div><div class="score-preview"><span>현재 응답 점수</span><strong>${sum(arr)} / ${max} · ${labeler()}</strong></div>`;
  container.querySelectorAll(".choice-button").forEach(btn=>btn.onclick=()=>{const i=Number(btn.dataset.index),v=Number(btn.dataset.value);arr[i]=v;if(arr===state.phq&&i===8&&v>0)openCrisis();render();});
}
function tierLabel(t){return t==="high"?"높은 주의가 필요해요":t==="mid"?"주의 깊게 살펴보세요":"현재 뚜렷한 고위험 신호는 낮아요";}
function riskCard(item){return `<article class="risk-card"><span>${item.label}</span><strong>${item.probability_pct.toFixed(1)}%</strong><div class="risk-level">${item.level_label}</div><div class="risk-meter"><i style="width:${Math.min(100,item.probability_pct)}%"></i></div></article>`;}
function renderSafety(){
  const p=sum(state.phq),g=sum(state.gad),k=sum(state.k10),tier=computeOverallTier(p,bandPHQ9(p),bandGAD7(g),bandK10(k),(state.phq[8]??0)>0,state.asq.some(Boolean));
  container.innerHTML=header("STEP 06 · SAFETY CHECK","마지막으로 안전을 확인할게요.","각 문항에 예 또는 아니오로 답해주세요. ‘예’ 응답 시 바로 도움 정보를 안내합니다.")+`<div class="question-list">${ASQ_ITEMS.map((q,i)=>`<article class="question-card"><p class="question-title"><span class="question-index">${String(i+1).padStart(2,"0")}</span><span>${q}</span></p><div class="yes-no"><button class="choice-button ${state.asq[i]===true?"selected":""}" data-i="${i}" data-v="true">예</button><button class="choice-button ${state.asq[i]===false?"selected":""}" data-i="${i}" data-v="false">아니오</button></div></article>`).join("")}</div><div class="summary-grid"><article class="summary-card"><span>PHQ-9</span><strong>${p}/27 · ${phqBandLabel(bandPHQ9(p))}</strong></article><article class="summary-card"><span>GAD-7</span><strong>${g}/21 · ${gadBandLabel(bandGAD7(g))}</strong></article><article class="summary-card"><span>K10</span><strong>${k}/50 · ${k10BandLabel(bandK10(k))}</strong></article></div>${state.loading?'<div class="loading-box">세 모델의 위험 신호를 분석하고 있습니다…</div>':""}${state.error?`<div class="error-box">${escapeHtml(state.error)}</div>`:""}${state.result?renderResult(state.result,tier):`<div class="result-banner ${tier.tier}"><h3>${tierLabel(tier.tier)}</h3><p>모든 안전 문항에 응답한 뒤 결과 분석 버튼을 눌러 ML 결과를 확인하세요.</p></div>`}`;
  container.querySelectorAll("[data-v]").forEach(b=>b.onclick=()=>{state.asq[Number(b.dataset.i)]=b.dataset.v==="true";if(b.dataset.v==="true")openCrisis();render();});
}
function renderResult(r,tier){return `<div class="result-banner ${r.overall_level}"><h3>${escapeHtml(r.summary)}</h3><p>${escapeHtml(r.recommendation)}</p></div><div class="risk-grid">${riskCard(r.predictions.suicidal)}${riskCard(r.predictions.depression)}${riskCard(r.predictions.stress)}</div><div class="result-actions"><a class="button button-primary" href="./map/지역_위험_지도.html?region=${encodeURIComponent(state.region)}" target="_blank">지역 인사이트 보기 ↗</a><button id="restart" class="button button-secondary">다시 시작</button></div>`;}
function render(){renderShell();if(state.step===0)renderRegion();else if(state.step===1)renderIntro();else if(state.step===2)renderScale("PHQ-9","지난 2주간의 우울 신호", "각 문항이 얼마나 자주 있었는지 선택해 주세요.",PHQ9A_ITEMS,state.phq,PHQ_GAD_CHOICES,27,()=>phqBandLabel(bandPHQ9(sum(state.phq))));else if(state.step===3)renderScale("GAD-7","지난 2주간의 불안 신호","평균적인 상태와 가장 가까운 응답을 선택해 주세요.",GAD7_ITEMS,state.gad,PHQ_GAD_CHOICES,21,()=>gadBandLabel(bandGAD7(sum(state.gad))));else if(state.step===4)renderScale("K10","지난 4주간의 스트레스 신호","각 감정을 얼마나 자주 경험했는지 선택해 주세요.",K10_ITEMS,state.k10,K10_CHOICES,50,()=>k10BandLabel(bandK10(sum(state.k10))));else renderSafety();const restart=$("restart");if(restart)restart.onclick=()=>location.reload();}

async function submit(){state.loading=true;state.error="";state.result=null;render();try{const response=await fetch(`${API_BASE}/predict`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phq_total:sum(state.phq),gad_total:sum(state.gad),k10_total:sum(state.k10),phq_item9:state.phq[8],asq_any_yes:state.asq.some(Boolean)})});const data=await response.json();if(!response.ok)throw new Error(data.detail?JSON.stringify(data.detail):`API 오류 ${response.status}`);state.result=data;$("live-status").textContent="위험 신호 분석이 완료되었습니다.";}catch(e){state.error=`결과를 불러오지 못했습니다. API 서버 상태를 확인해 주세요.\n${e.message}`;}finally{state.loading=false;render();}}
function openCrisis(){modal.hidden=false;document.body.style.overflow="hidden";$("crisis-later-btn").focus();}function closeCrisis(){modal.hidden=true;document.body.style.overflow="";}
$("crisis-later-btn").onclick=closeCrisis;$("crisis-connect-btn").onclick=closeCrisis;document.querySelector("[data-close-modal]").onclick=closeCrisis;document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!modal.hidden)closeCrisis();});
prev.onclick=()=>{if(state.step>0){state.step--;state.result=null;render();scrollTo({top:0,behavior:"smooth"});}};next.onclick=()=>{if(!complete())return;if(state.step<5){state.step++;render();scrollTo({top:0,behavior:"smooth"});}else submit();};render();
